package com.unla.arbolado;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import com.unla.arbolado.SQLite.ArbolSQLite;
import com.unla.arbolado.modelo.Arbol;

public class ArbolActivity extends AppCompatActivity {

    private Spinner s_especie;
    private EditText et_numeroarbol;
    private EditText et_distanciaplantas;
    private EditText et_distanciamuro;
    private EditText et_circunferencia;
    private Spinner s_cazuela;
    private EditText et_comentario;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_arbol);

        s_especie = findViewById(R.id.s_especie);
        et_numeroarbol = findViewById(R.id.et_numeroarbol);
        et_distanciaplantas = findViewById(R.id.et_distanciaplantas);
        et_distanciamuro = findViewById(R.id.et_distanciamuro);
        et_circunferencia = findViewById(R.id.et_circunferencia);
        s_cazuela = findViewById(R.id.s_cazuela);
        et_comentario = findViewById(R.id.et_comentario);

        String[] op_especie = {"Especie", "OTRO", "DESCONOCIDA",
                "Alamo blanco piramidal",
                "Alamo carolina",
                "Alamo de Italia",
                "Alamo negro del Canada",
                "Alamo plateado",
                "Arbol del amor (Ciclamor o  Arbol de Judas)",
                "Arbol del cielo (Ailanto o Arbol de los dioses)",
                "Arbol del humo",
                "Arbol fuccia",
                "Abedul blanco",
                "Abedul comun (Abedul de Europa o Abedul verrugoso)",
                "Abutilo",
                "Acacia",
                "Acacia blanca",
                "Acacia bola",
                "Acacia de Baile (Mimosa de Baile)",
                "Acacia de constantinopla",
                "Acacia frisia",
                "Acacia negra",
                "Acacia rosada",
                "Acacia verde",
                "Adelfa amarilla",
                "Aesculus",
                "Afrocarpus",
                "Agatis blanco",
                "Agave vivipara",
                "Aguaribay",
                "Ahuehuete",
                "Alamo",
                "Alamo negro",
                "Alcanforero",
                "Alcornoque",
                "Algarrobo",
                "Algarrobo Blanco",
                "Aliso de ra¬o",
                "Almez (Almecino o Almecina)",
                "Almez de china",
                "Añangapira¬ (Grosella o Cereza de Cayena)",
                "Aralia",
                "Aralia elegantisima",
                "Aralia variegada",
                "Araucaria",
                "Araucaria (Araucaria de pisos)",
                "Araucaria columnar",
                "Arbol de las orquideas",
                "Arbol de las pasas",
                "Arbol del pomelo",
                "Arce",
                "Arce blanco",
                "Arce campestre (Arce comun o  Arce menor)",
                "Arce japones",
                "Arce negundo",
                "Arce plateado (Arce blanco)",
                "Arce real",
                "Arce tridente",
                "Areca",
                "Arizanica (Cipres de Arizona)",
                "Aromo",
                "ArrayAn (Anacahuita)",
                "Aruera",
                "Avellano comun",
                "Azarero",
                "Bananero",
                "Betula",
                "Boj cepillo",
                "Boj comun",
                "Bola de nieve",
                "Boungavillea",
                "Brachichito rosa",
                "Brachichiton (Arbol botella, Brachichito)",
                "Braquiquito",
                "Bunya-bunya (Araucaria de Bidwill)",
                "Caesalpinia",
                "Callistemon",
                "Camelia",
                "camellia",
                "Canela de venado",
                "Canelan",
                "Caoba del sur",
                "Capparis",
                "Caqui",
                "Caranday",
                "Carnaval(Vainillo)",
                "Casia (Rama negra)",
                "Cassia",
                "Castaño de Indias comun",
                "Casuarina",
                "Catalpa",
                "Catalpa",
                "Cedrela",
                "Cedro",
                "Cedro azulado",
                "Cedro blanco de California",
                "Cedro de San Juan",
                "Cedro del Atlas (Cedro plateado)",
                "Cedro del Himalaya",
                "Cedro del Himalaya variedad aurea",
                "Cedro del LA¬bano  (Cedro de Salomon)",
                "Cedro misionero (Cedro colorado)",
                "Cefalotaxus",
                "Ceibo",
                "Ceibo",
                "Ceibo del monte",
                "Celtis tala",
                "Celtis tala",
                "Cerella",
                "Cerezo",
                "Chal Chal",
                "Chamaecyparis",
                "Cheflera",
                "Cica",
                "Cina cina",
                "Cinnamomun",
                "Cipres",
                "Cipres blanco",
                "Cipres fanebre (Lloron chino)",
                "Cipres funerario",
                "Cipres horizontal",
                "Cipres leylandi",
                "Cipres piramidal",
                "Cipres",
                "Cipres calvo",
                "Ciruelo",
                "Ciruelo de jardin",
                "Citricos",
                "Coculus",
                "Corona de cristo",
                "Coronillo",
                "Cotoneaster",
                "Cotoneaster",
                "Cotoneaster",
                "Crataegus",
                "Crataegus",
                "Crespon ",
                "Criptomeria (Cedro del Japon)",
                "Curupa",
                "Dracena indivisa",
                "Dracena marginata",
                "dracaena",
                "Duranta",
                "Duranta variedad aurea",
                "Durazno",
                "El chañar",
                "Eleagno",
                "Eleagnus",
                "Encina",
                "Enebro comun",
                "Enterolobium",
                "Espina del bañado",
                "Espinillo (Aromo)",
                "Espino de fuego",
                "Espino de fuego",
                "Esterculea",
                "Estrella federal",
                "Eucalipto",
                "Eucalipto",
                "Eucalipto (Eucalipto comun)",
                "Eucalipto cinerea",
                "Eucalipto saligna",
                "Eucalipto sideroxylon",
                "Eucalipto tereticornis",
                "Euforbia",
                "Euphorbia",
                "Falso Alcanforero",
                "Falso alerce",
                "Falso cafeto",
                "Falso cipres de Lawson",
                "Falso Guayabo (Guayaba del Brasil)",
                "Fenix",
                "Fenix",
                "Fenix paludosa",
                "Ficus",
                "Ficus",
                "Ficus ali",
                "Ficus herrumbroso (Ficus oxidado o Higuera herrumbrosa)",
                "Ficus variegado",
                "Firmiana",
                "Fotinia",
                "Fotinia",
                "Fotinia",
                "Fresno",
                "Fresno (Fresno comun)",
                "Fresno americano",
                "Ginkgo",
                "Gomero",
                "Granado",
                "Grevillea",
                "Guabiyi",
                "Guaran amarillo",
                "Guayabo",
                "Guayaibi",
                "Hibiscus",
                "Higuera",
                "Higuera de Baha¬a",
                "Higueron",
                "IbirA pitA",
                "Ilex",
                "Inga",
                "Jazmin",
                "Jazmin del Paraguay",
                "Jazmin naranja",
                "Juglans",
                "Juniperus",
                "Juniperus",
                "Kauri de corteza lisa",
                "Lagunaria (Arbol pica-pica)",
                "Lapachillo",
                "Lapacho",
                "Lapacho amarillo",
                "Lapacho negro",
                "Lapacho rosado",
                "Laurel",
                "Laurel blanco",
                "Laurel cerezo",
                "Laurel de indias",
                "Laurel de jardin (Laurel de flor)",
                "Laurel del rio",
                "Laurus",
                "Libocedro (Calocedro)",
                "Libocedrus",
                "Ligustrina",
                "Ligustrina de California",
                "Ligustro",
                "Ligustro disciplinado (Ligustro variegado)",
                "Ligustrum",
                "Limonero",
                "Limpiatubos",
                "Liquidambar",
                "Livistona de China (Palmera china de abanico)",
                "Macrocarpa ",
                "Magnolia",
                "Magnolia",
                "Malus",
                "Mandarino",
                "Mataojos",
                "Membrillero",
                "Mimosa (Aromo frances)",
                "Mirto",
                "Morera blanca",
                "Morera de papel (Moral de China)",
                "Morera negra",
                "Morera pendula",
                "Morus",
                "Naranjillo",
                "Naranjo amargo",
                "Naranjo de Luisana",
                "Naranjo dulce",
                "Nerium",
                "Nipero japones",
                "No Determinado",
                "Nogal americano",
                "Nogal criollo",
                "Nogal europeo (Nogal comun)",
                "Nolina",
                "Olea",
                "Olivo",
                "Olivo oloroso",
                "Olmo",
                "Olmo",
                "Olmo de montaña",
                "Olmo europeo",
                "Ombu",
                "Ombu",
                "PA¡tano de Oriente (PAtano oriental)",
                "Palma Bangalow  (Palma Rey)",
                "Palma de california",
                "Palmera china",
                "Palmera del senegal",
                "Palmera enana",
                "Palmito",
                "Palo amarillo",
                "Palo amarillo",
                "Palo borracho",
                "Palo borracho blanco",
                "Palo borracho rosado",
                "Palo coca",
                "Palto",
                "Paraiso",
                "Paraiso umbraculifera",
                "Parasol de la china",
                "Pata de vaca  (Pezuña de vaca)",
                "Paulonia (Arbol de la emperatriz)",
                "Pecan",
                "Peltophorum",
                "Peral comun",
                "Phyllanthus",
                "Picea",
                "Pindo",
                "Pino",
                "Pino",
                "Pino carrasco (Pino de Jerusalen)",
                "Pino de las canarias",
                "Pino de Siberia",
                "Pino del ParanA (Pino de Misiones o Pino de Brasil)",
                "Pino piñonero",
                "Pino rodeno",
                "PlAtano",
                "Plumerillo rojo",
                "Podocarpus",
                "Poinciana (Caesalpinia o Barba de chivo)",
                "Prosopis",
                "Prunus",
                "Quebracho colorado",
                "Quinoto",
                "Rafis (Palmerita china)",
                "Robinia",
                "Roble",
                "Roble americano",
                "Roble comun",
                "Roble palustre",
                "Roble sedoso (Grevillea)",
                "Robusta",
                "Rosa de China (Hibisco)",
                "Rosa de mayo",
                "Rosa de Siria",
                "Ruprechtia",
                "Rus",
                "Safora japonica",
                "Safora pandula",
                "Sambucus",
                "Sauce",
                "Sauce blanco",
                "Sauce blanco variedad tristis",
                "Sauce criollo",
                "Sauce electrico",
                "Sauce lloron",
                "Sauzgatillo",
                "Schinus",
                "Secuoya",
                "Sesbania",
                "Siempreverde",
                "Sota Caballo",
                "Tabaco ornamental",
                "Tabaquillo",
                "Taxodium",
                "Taxus",
                "Tejo chino",
                "Tilo",
                "Tilo",
                "Timba (Oreja de negro)",
                "Tipa blanca",
                "Trachycarpus",
                "Trichilia",
                "Tuja",
                "Tulipanero",
                "Tuya",
                "Tuya oriental",
                "Viburnum",
                "Viburnum dulce",
                "Virara (Virara crespo)",
                "Visco (Viscote, Arca)",
                "Washingtonia",
                "washingtonia",
                "Washingtonia (Palmera)",
                "Yuca"};
        String[] op_cazuela = {"Cazuela","NO", "SI"};

        ArrayAdapter<String> ad_especie = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_dropdown_item, op_especie);
        ArrayAdapter<String> ad_cazuela = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_dropdown_item, op_cazuela);

        s_especie.setAdapter(ad_especie);
        s_cazuela.setAdapter(ad_cazuela);
    }

    public void continuar(View view) {
        String especie = s_especie.getSelectedItem().toString();
        String numeroarbol = et_numeroarbol.getText().toString();
        String distanciaplantas = et_distanciaplantas.getText().toString();
        String distanciamuro = et_distanciamuro.getText().toString();
        String circunferencia = et_circunferencia.getText().toString();
        String cazuela = s_cazuela.getSelectedItem().toString();
        String comentario = et_comentario.getText().toString();

        if (numeroarbol.isEmpty()) {
            Toast.makeText(this, "Debes completar el numero de arbol", Toast.LENGTH_SHORT).show();
        }
        else {
            if (distanciaplantas.isEmpty())
                distanciaplantas = "0";
            if (distanciamuro.isEmpty())
                distanciamuro = "0";
            if (circunferencia.isEmpty())
                circunferencia = "0";

            long id = ArbolSQLite.getInstance(this).agregar(new Arbol(especie, Integer.parseInt(numeroarbol), Float.parseFloat(distanciaplantas), Float.parseFloat(distanciamuro), Float.parseFloat(circunferencia), cazuela, comentario));
            Toast.makeText(getApplicationContext(), "ID registro: " + id, Toast.LENGTH_SHORT).show();

            Intent intent = new Intent(this, EstadoActivity.class);
            intent.putExtra("idUsuario", getIntent().getLongExtra("idUsuario", 0));
            intent.putExtra("idCalle", getIntent().getLongExtra("idCalle", 0));
            intent.putExtra("idArbol", id);
            startActivity(intent);
        }
    }

}
